name: BattleEquipControl
main: me.kapehh.BattleEquipControl.Main
author: kapehh
version: 1.0.0
commands:
    battleequip:
        usage: /<command> convert
        description: Read manual
        aliases: bec