name: BattleEquipControl
main: me.kapehh.BattleEquipControl.Main
author: kapehh
version: 1.0.0
#commands:
#    arenascript:
#      usage: /<command> <arena> <player>
#      description: Simple Arena Script